### ISSUE TITLE
Incorrect Event Code Mapping

### ISSUE THREAD

**Issue by henrygrover** [ManageIQ/ovirt#70]
Hi,

Unless I'm missing something, it seems that one of the event codes (533=>"HOST_FAILED_CONNECTION_TO_DATA_CENTER") is incorrect. the RHEV documentation lists that as "VDS_HIGH_NETWORK_USE", which I would expect to map to "HOST_HIGH_NETWORK_USE" given the general pattern with the other codes. Was this renaming intentional?

https://github.com/ManageIQ/ovirt/blob/master/lib/ovirt/event.rb#L309 is where it's set here

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.5/html/Technical_Guide/appe-Event_Codes.html#Event_Codes is where it's listed as something different

Thanks!

**Comment by pkliczewski** [comment]
You are correct the mapping is wrong please see [the engine](https://github.com/oVirt/ovirt-engine/blob/master/backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/AuditLogType.java#L43)

**Comment by henrygrover** [comment]
@pkliczewski Thanks for your help with that. I actually parsed through the file you linked using sed and found a number of other differences. Should I submit those as a PR? Is there a limited subset of event codes from the engine that this gem wants to map?

**Comment by pkliczewski** [comment]
@henrygrover Some of the event handling may be not implemented so I wouldn't add any new event codes but if you see any other inconsistencies please let me know and I will be happy to update my PR.

**Comment by henrygrover** [comment]
@pkliczewski here are the rest, filtering out any difference that just came down to HOST vs VDS. Name on the left is straight from event.rb, name on the right is from AuditLogType.java. If it would be helpful, I can send the script I used to generate these. It pulls in the two files directly and goes from there.

Some of these are probably intentional differences, but I figured I would put them all in here just in case.

Ruby--USER_REMOVE_VM, Java--USER_ADD_VM_TEMPLATE_FAILURE
Ruby--USER_HOST_SHUTDOWN, Java--HOST_FAILED_TO_GET_HOST_HARDWARE_INFO
Ruby--VM_MIGRATION_FAILED_FROM_TO, Java--VM_MIGRATION_TO_SERVER_FAILED
Ruby--USER_FAILED_HOST_SHUTDOWN, Java--USER_SUSPEND_VM_FINISH_FAILURE_WILL_TRY_AGAIN
Ruby--VM_MIGRATION_FAILED_DURING_MOVE_TO_MAINTANANCE, Java--VM_MIGRATION_FAILED_DURING_MOVE_TO_MAINTENANCE
Ruby--VM_BLK_VIRTIO_NO_CACHE, Java--VM_PAUSED_EIO
Ruby--VM_SHUTDOWN_FAILED, Java--VM_POWER_DOWN_FAILED
Ruby--USER_MERGE_SNAPSHOT, Java--USER_REMOVE_SNAPSHOT
Ruby--USER_FAILED_MERGE_SNAPSHOT, Java--USER_FAILED_REMOVE_SNAPSHOT
Ruby--USER_MERGE_SNAPSHOT_FINISHED_SUCCESS, Java--USER_REMOVE_SNAPSHOT_FINISHED_SUCCESS
Ruby--USER_MERGE_SNAPSHOT_FINISHED_FAILURE, Java--USER_REMOVE_SNAPSHOT_FINISHED_FAILURE
Ruby--USER_DETACH_USER_FROM_TIME_LEASED_POOL_INTERNAL, Java--USER_ATTACH_TAG_TO_TEMPLATE_EXISTS
Ruby--AUTO_SUSPEND_VM_FINISH_SUCCESS, Java--HOST_INITIATED_RUN_AS_STATELESS_VM_NOT_YET_RUNNING
Ruby--HOST_FAILED_CONNECTION_TO_DATA_CENTER, Java--HOST_HIGH_NETWORK_USE
Ruby--HOST_USED_AS_PROXY, Java--PROXY_HOST_SELECTION
Ruby--USER_ADD_HOST_GROUP, Java--USER_ADD_CLUSTER
Ruby--USER_ADD_HOST_GROUP_FAILED, Java--USER_ADD_CLUSTER_FAILED
Ruby--USER_UPDATE_HOST_GROUP, Java--USER_UPDATE_CLUSTER
Ruby--USER_UPDATE_HOST_GROUP_FAILED, Java--USER_UPDATE_CLUSTER_FAILED
Ruby--USER_REMOVE_HOST_GROUP, Java--USER_REMOVE_CLUSTER
Ruby--USER_REMOVE_HOST_GROUP_FAILED, Java--USER_REMOVE_CLUSTER_FAILED
Ruby--USER_DEDICATE_VM_TO_POWERCLIENT, Java--USER_VDC_SESSION_TERMINATED
Ruby--USER_DEDICATE_VM_TO_POWERCLIENT_FAILED, Java--USER_VDC_SESSION_TERMINATION_FAILED
Ruby--SYSTEM_UPDATE_HOST_GROUP, Java--SYSTEM_UPDATE_CLUSTER
Ruby--SYSTEM_UPDATE_HOST_GROUP_FAILED, Java--SYSTEM_UPDATE_CLUSTER_FAILED
Ruby--NETWORK_ADD_BOND_FAILED, Java--MAC_ADDRESS_IS_EXTERNAL
Ruby--NETWORK_ATTACH_NETWORK_TO_HOST_GROUP, Java--NETWORK_ATTACH_NETWORK_TO_CLUSTER
Ruby--NETWORK_ATTACH_NETWORK_TO_HOST_GROUP_FAILED, Java--NETWORK_ATTACH_NETWORK_TO_CLUSTER_FAILED
Ruby--NETWORK_DETACH_NETWORK_TO_HOST_GROUP, Java--NETWORK_DETACH_NETWORK_TO_CLUSTER
Ruby--NETWORK_DETACH_NETWORK_TO_HOST_GROUP_FAILED, Java--NETWORK_DETACH_NETWORK_TO_CLUSTER_FAILED
Ruby--ISO_DOMAIN_REFRESH_SUCCESSFUL, Java--REFRESH_REPOSITORY_IMAGE_LIST_SUCCEEDED
Ruby--NETWORK_INTERFACE_PLUGGED_INTO_VM, Java--NETWORK_ACTIVATE_VM_INTERFACE_SUCCESS
Ruby--NETWORK_UPDATE_DISPLAY_TO_HOST_GROUP, Java--NETWORK_UPDATE_DISPLAY_TO_CLUSTER
Ruby--NETWORK_UPDATE_DISPLAY_TO_HOST_GROUP_FAILED, Java--NETWORK_UPDATE_DISPLAY_TO_CLUSTER_FAILED
Ruby--VM_RENAMED, Java--ENTITY_RENAMED
Ruby--HOST_ALERT_FENCING_IS_NOT_CONFIGURED, Java--HOST_ALERT_FENCE_IS_NOT_CONFIGURED
Ruby--HOST_ALERT_FENCING_TEST_FAILED, Java--HOST_ALERT_FENCE_TEST_FAILED
Ruby--HOST_ALERT_FENCING_OPERATION_FAILED, Java--HOST_ALERT_FENCE_OPERATION_FAILED
Ruby--HOST_ALERT_FENCING_OPERATION_SKIPPED, Java--HOST_ALERT_FENCE_OPERATION_SKIPPED
Ruby--HOST_ALERT_FENCING_NO_PROXY_HOST, Java--HOST_ALERT_FENCE_NO_PROXY_HOST

**Comment by henrygrover** [comment]
@bdunne should any of the rest of these be updated as well?

**Comment by bdunne** [comment]
@henrygrover If they are incorrect or outdated for the latest Ovirt 3.x version, yes.

**Comment by henrygrover** [comment]
@bdunne I checked against the ovirt-engine master branch. I'll re-run everything with latest 3.x (3.6.9) when I get a chance and make a PR.

Are some of the differences between ovirt-engine event names and ovirt gem event names intentional? For example, the change of "VDS" to "HOST" or "FENCING" to "FENCE". If there's a way to determine which changes are intentional I can just filter those out.

**Comment by bdunne** [comment]
@henrygrover This was built against Ovirt 3.0 and I haven't seen many changes to this event map.  I assume that most of the differences are changes in Ovirt that were never implemented in this gem.

**Comment by pkliczewski** [comment]
@henrygrover In ovirt due to legacy reasons we name a host as vds and a cluster as host_group. I would agree here that they were changed intentionally. I still see some that would need to be changes:

> USER_REMOVE_VM, **USER_ADD_VM_TEMPLATE_FAILURE**

> USER_HOST_SHUTDOWN, **HOST_FAILED_TO_GET_HOST_HARDWARE_INFO**

> VM_BLK_VIRTIO_NO_CACHE, **VM_PAUSED_EIO**

> HOST_FAILED_CONNECTION_TO_DATA_CENTER, **HOST_HIGH_NETWORK_USE**

> NETWORK_ADD_BOND_FAILED, **MAC_ADDRESS_IS_EXTERNAL**

> VM_RENAMED, **ENTITY_RENAMED**

Feel free to create a PR or let me know so I will do it.
