### ISSUE TITLE
Provided examples don't work

### ISSUE THREAD

**Issue by vide** [ManageIQ/ovirt#86]
This is what I get when I'm trying to run the examples found in the `examples` directory:

```bash
$ ruby create_vm_example.rb 
/home/vide/git/work/forks/ovirt/lib/ovirt/logging.rb:3:in `<module:Logging>': undefined method `delegate' for Ovirt::Logging:Module (NoMethodError)
Did you mean?  DelegateClass
	from /home/vide/git/work/forks/ovirt/lib/ovirt/logging.rb:2:in `<module:Ovirt>'
	from /home/vide/git/work/forks/ovirt/lib/ovirt/logging.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/vide/git/work/forks/ovirt/lib/ovirt.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vide/git/work/forks/ovirt/examples/example_helper.rb:2:in `<top (required)>'
	from create_vm_example.rb:1:in `require_relative'
	from create_vm_example.rb:1:in `<main>'
```

Ruby: `ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]`, gem installed with `gem install ovirt`

**Comment by masayag** [comment]
@bdunne the described issue occurred since 'ovirt'  doesn't include ActiveSupport.
in ovirt/logging.rb there is a use of the 'delegate' which requires ActiveSupport:
```
  module Logging
    delegate :logger, :to => :Ovirt
  end
```

How would you suggest to bypass it ? (include ActiveSupport or use an alternate delegation method)

**Comment by bdunne** [comment]
@masayag I'd rather not add the dependency on ActiveSupport for that.  What do you think of this instead?
```ruby
module Logging
  def logger
    Ovirt.logger
  end
end
```

**Comment by masayag** [comment]
@bdunne looks good.

Add PR here: https://github.com/ManageIQ/ovirt/pull/87

**Comment by masayag** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error in invoking ovirt-gem examples](https://trello.com/c/u33UX6X4/184-error-in-invoking-ovirt-gem-examples)

**Comment by bdunne** [comment]
Thanks @vide v0.18.0 is now released with these changes
