### ISSUE TITLE
How to export a VM?

### ISSUE THREAD

**Issue by mrmarbury** [ManageIQ/ovirt#90]
I am trying to do a vm export which always fails with the message 

```
gems/ovirt-0.18.1/lib/ovirt/service.rb:356:in `parse_error_response': Action [storageDomain.id|name] required for export (Ovirt::Error)
```

My code looks as follows:

```
ovirt = OvirtHelper.service
vm = Ovirt::Vm.find_by_name ovirt, 'chef'
action = vm.export
```
I tried different ways to attach the storage domain for the export. As an object, as a string, etc. But the error stays the same. 

I didn't find an example on how to correctly do an export. Could you please help me out here because I am kinda stuck?

Cheers,
Stefan

**Comment by masayag** [comment]
@mrmarbury would you consider using ovirt-engine-sdk-ruby as a client to ovirt-engine and follow this example: 

https://github.com/oVirt/ovirt-engine-sdk-ruby/blob/master/sdk/examples/export_vm.rb

ovirt-engine-sdk is the format supported client for ovirt-engine and is the most updated one.

If you'd like to use ovirt gem, you can try adding the missing parameter as expected in [1], although the documentation is of an advanced api version.

specifically it might be similar to:
```
action = vm.export(storage_domain: { name: 'myexport'  })
```


[1] http://ovirt.github.io/ovirt-engine-api-model/4.1/#services/vm/methods/export

**Comment by mrmarbury** [comment]
I will try the ovirt-engine-api for now. Hopefully this feature will work for ovirt 3.6 as well because that is the version I need it for.

**Comment by masayag** [comment]
@mrmarbury please report back if 
```
action = vm.export(storage_domain: { name: 'myexport'  })
```
solved the issue, so this issue can be closed, or a different parameters should be specified.

**Comment by mrmarbury** [comment]
Well, it works when I bypass method_missing and directly use

`vm.operation(:export) { |xml| xml.storage_domain { xml.name 'Export' } }`

So I think the `method_missing` should be enhanced to pass the block to `operation()`?

**Comment by masayag** [comment]
@borod108 please have a look at this issue

**Comment by mrmarbury** [comment]
I have no easy way to submit a pull request from the customer system here but for now I have monkey patched it and the export function looks like this:

```
def export(storage_domain)
      response = operation(:export) do |xml|
        xml.storage_domain(:id => self.class.object_to_id(storage_domain))
      end
      doc    = Nokogiri::XML(response)
      action = doc.xpath("//action/job").first
      raise Ovirt::Error, "No Action in Response: #{response.inspect}" if action.nil?
      action['href']
    end
```
So it is pretty similar to the `move()` method except for the `:export`-Symbol and the xpath which has to be `"//action/jobs"`.  When you want to check for the status you have to check for `"FINISHED"`

Hope that makes implementation for you guys easier?

**Comment by agrare** [comment]
Hey @gekorob could you take a look at this?

**Comment by gekorob** [comment]
Hi @agrare, sure I'll look at it in the next few days

**Comment by gekorob** [comment]
Closing 'cause fixed by https://github.com/ManageIQ/ovirt/pull/92
